### ISSUE TITLE
Break door

### ISSUE THREAD

**Issue by lucasfelipe-sh** [benfah/DoorsOfInfinity#1]
When you break a door, and place it again, instead it autodetect the first door you opened, it will create completely new Infinity structure.
I know probably it's very hard to program, but it's a very important detail.

Nice mod!

Best regards :)

**Comment by benfah** [comment]
This is weird. I have programmed that feature into the game :/. Could you send me your MC version, Immersive Portals version and Doors of Infinity version? And how did you break the door? (Upper/Lower side of the door, a frame block)

**Comment by lucasfelipe-sh** [comment]
Of course I can! 
Minecraft ver: 1.15.2
Fabric: 0.8.2 build 194 - 1.15.2
Immersive Portals: 0.27 - 1.15.2
Doors of Infinity: 1.0.3 - 1.15.2

I had break the door in Creative Mode, but I can't remember if I had break it in the upper or lower side :/
I'm really sorry, but I break it on the Overworld dimension.

**Comment by benfah** [comment]
Is it possible that you didn‘t use the correct door? There are two types of doors: One player-makeable door and a unbreakable door that will automatically generate. The player-makeable is the only one that will drop when broken. This type of door should be in the creative menu and has the id „doorsofinfinity:simulated_infinity_door“

**Comment by benfah** [comment]
I'm gonna see this as fixed
