### ISSUE TITLE
May I take ownership of this project and maintain it?

### ISSUE THREAD

**Issue by froyo4u** [benfah/DoorsOfInfinity#23]
This mod has sadly been abandoned but may I continue to maintain it for you?

**Comment by Scwestbrook** [comment]
I would love it if you did!!! Edit: Just so you know, I'm not the mod owner, but I would enjoy to see this mod continue.

**Comment by benfah** [comment]
Hi, sorry for replying so late. Well, how do I start. This whole mod thing is pretty new for me. I've done some projects here and there but they never really "blew up" or dragged any big amount of attention to them, I've never encountered this type of situation where people actually ask me to continue the mod, and sadly I have the tendency to take breaks from programming sometimes when I feel "pressured" even though people are not really enforcing this on me. I really enjoy programming, so I'd still like to continue the project, but if you'd like to contribute something, i'll be open for it :D.

**Comment by froyo4u** [comment]
> Hi, sorry for replying so late. Well, how do I start. This whole mod thing is pretty new for me. I've done some projects here and there but they never really "blew up" or dragged any big amount of attention to them, I've never encountered this type of situation where people actually ask me to continue the mod, and sadly I have the tendency to take breaks from programming sometimes when I feel "pressured" even though people are not really enforcing this on me. I really enjoy programming, so I'd still like to continue the project, but if you'd like to contribute something, i'll be open for it :D.

Cool, sorry if I bothered you or anything. If there's anything that I manage to see first, I would happily contribute. 😄
