### ISSUE TITLE
Mobs spawning on the roof

### ISSUE THREAD

**Issue by NafelSquared** [benfah/DoorsOfInfinity#4]
Hello !
I don't know if this is a bug or if it is intented, but mobs (hostile and passive) are spawning on the roof of the box.
(it's maybe because I use mods and it broke something, I don't know... also I love your mod *3* ) 
Have a good day/evening/night !

**Comment by benfah** [comment]
May be other mods. I still disabled the mob spawning just to make sure no mobs will spawn :) (Will roll out with the next update)
