### ISSUE TITLE
Server Crash on Startup (Forge)

### ISSUE THREAD

**Issue by CHead2000** [benfah/DoorsOfInfinity#8]
I concluded that this mod was causing my server to crash because it started up when I removed it from the mod list. I've attached my crash report, log, and debug for the server.

[Crash Report.txt](https://github.com/benfah/DoorsOfInfinity/files/4606584/Crash.Report.txt)
[Debug.log](https://github.com/benfah/DoorsOfInfinity/files/4606586/Debug.log)
[Log.txt](https://github.com/benfah/DoorsOfInfinity/files/4606583/Log.txt)

**Comment by benfah** [comment]
Fixed!
