### ISSUE TITLE
Server Crash on load 1.0.0 forge

### ISSUE THREAD

**Issue by deadspidervenom** [benfah/DoorsOfInfinity#9]
TL;DR Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER

here is the log that involves the crash
https://pastebin.com/SiX2t9N0

Here is the crash log

https://pastebin.com/r11VMTBH

**Comment by benfah** [comment]
Should be fixed with the new update! :D
